### ISSUE TITLE
peerDeps still point at older karma

### ISSUE THREAD

**Issue by gkatsev** [karma-runner/grunt-karma#267]
It was great to see a new release of grunt-karma, looking into it, it seems that the peerDependencies are still pointing at karma 0.13 and 1.0 https://github.com/karma-runner/grunt-karma/blob/v3.0.0/package.json#L50-L53 and https://registry.npmjs.org/grunt-karma/3.0.0

It sounds like that was the plan for this release (#261), though, maybe there's some background I'm missing.

Thanks!

**Comment by Krinkle** [comment]
@gkatsev Thanks, yeah, it was planned and is pending review at <https://github.com/karma-runner/grunt-karma/pull/264>. 

In my own testing, it seems to actually work fine because npm no longer downloads peerDependencies (which is good), instead it is the project's own responsibility to install the preferred version.

As such, if you specify karma 3.0.0 with grunt-karma 3.0.0, then it will actually use those together, it shouldn't install karma 1.x, and it also shouldn't refuse to use the karma 3.0 version.

But, of course, it does cause a warning, and that's wrong. We instead should print a warning when the project is using a karma version that is not 3.x. One the linked PR lands, I recommend we do a minor release to make it available.

**Comment by gkatsev** [comment]
Ah, must've missed that PR. Yeah, npm no longer forces peerDeps which is good.

Thanks for the info!

**Comment by jbanulso** [comment]
It works fine, but when running `yarn check` an error is thrown:
```
error "grunt-karma#karma@^0.13.0 || ^1.0.0" doesn't satisfy found match of "karma@3.1.1"
```
Great if #264 could be released!

**Comment by Krinkle** [comment]
Done!

**Comment by jbanulso** [comment]
Will there be a patch release soon to reflect these changes?
